server:
  port: 18082
  servlet:
    context-path: /api/
spring:
  data:
    mongodb:
      database: all-docs
#      username:
#      password:
#      host: localhost
#      port: 27017
      uri: mongodb://127.0.0.1:27017/all-docs
      threads-allowed-to-block-for-connection-multiplier: 20
      connect-timeout: 10000
      socket-timeout: 10000
      max-wait-time: 5000
      connections-per-host: 20
  datasource:
    url: jdbc:mysql://localhost:13306/all-docs?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=CST
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    password:
    port: 16379
    timeout: 3000
    jedis:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池中的最小空闲连接
        min-idle: 50
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1000
    testOnBorrow: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  thymeleaf:
    mode: HTML
    cache: false
cloud:
  elasticsearch:
    host: localhost
    port: 9200
#    host: 81.69.247.172
#    port: 8888
jwt:
  secret: C*F-JaNdRgUkXn2r5u8x/A?D(G+KbPeShVmYq3s6v9y$B&E)H@McQfTjWnZr4u7w
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  config: classpath:logback.xml